### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by andywalden** [andywalden/esmcheckds2#1]
> esmdscheck2.exe -sdfsdfs

    Traceback (most recent call last):
    File "esmcheckds2\console.py", line 57, in <module>
    File "esmcheckds2\console.py", line 17, in main
    ValueError: dictionary update sequence element #0 has length 1; 2 is required
    Failed to execute script console

**Comment by andywalden** [comment]
Fixing with Click implentation

**Comment by andywalden** [comment]
Fixed
