### ISSUE TITLE
Improve error handling - mfe_saw.ini

### ISSUE THREAD

**Issue by andywalden** [andywalden/esmcheckds2#2]
(esmcheckds2-1) krampus:~$ esmcheckds2
Traceback (most recent call last):
  File "/home/test/esmcheckds2-1/bin/esmcheckds2", line 11, in <module>
    sys.exit(main())
  File "/home/test/esmcheckds2-1/lib/python3.5/site-packages/esmcheckds2/console.py", line 12, in main
    host = config.esm_host
AttributeError: 'Config' object has no attribute 'esm_host'
(esmcheckds2-1) krampus:~$ cat .mfe_saw.ini
[esm]
esmhost=10.0.0.3  <--wrong key - should be esm_host

**Comment by andywalden** [comment]
Still wrong key, should me esmhost as in: https://github.com/andywalden/esmcheckds2/issues/4

Still needs better error handling.
